#-------------------------------
# General Site Settings
title: Jarvin Mutatiina
logo: logo.svg# You can add own logo.
description: Personal Website


#-------------------------------
# Author Settings
author:
  name: Jarvin Mutatiina
  image: jarvinMutatiina.jpg
  say-hello: Hello, Iâ€™m <strong>Jarvin</strong>
  bio: A <strong>data science enthusiast</strong> and all around <strong>technologist</strong>.<br><br>  Passionate, analytical, innovative and creative. MSc Computing Science graduate from the <b> University of Groningen</b>. When I am not on my computer jumping from a code editor to YouTube to Stack Overflow to Spotify, I am out in the world exploring sites, nature and food with friends.


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
linkedin: https://www.linkedin.com/in/jarvin-mutatiina-038451107/
github: https://github.com/Jarvin-M
email: mailto:jarvinm19@gmail.com


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: jarvin-me # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile:  # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: UA-131311430-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e